package fried.rice.shop;
import java.sql.* ;
import java.sql.ResultSet;
import javax.swing.* ;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author vijiganesan
 */
public class BILLING extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement stmt1=null;
    PreparedStatement stmt2=null;
    ResultSet generatedkey;
    /**
     * Creates new form BILLING
     */
    public BILLING() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    DefaultTableModel model=new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_customername = new javax.swing.JLabel();
        tf_customername = new javax.swing.JTextField();
        lb_mobileno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tf_product = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lb_product = new java.awt.Label();
        lb_qty = new javax.swing.JLabel();
        tf_qty = new javax.swing.JTextField();
        add_b1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        print_b2 = new javax.swing.JToggleButton();
        exit_b3 = new javax.swing.JToggleButton();
        tf_subtotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b2_delete = new javax.swing.JButton();
        tf_mobileno = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel2.setText("Customer Details");

        lb_customername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_customername.setText("Customer Name");

        lb_mobileno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_mobileno.setText("Mobile No");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tf_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Poni", "ponmani", "zera rice", "karnataka poni", "andhra poni", "co43" }));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setText("Sales Dhasboard");

        lb_product.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_product.setText("Select Product");

        lb_qty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_qty.setText("Quantity");

        tf_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_qtyKeyTyped(evt);
            }
        });

        add_b1.setForeground(new java.awt.Color(255, 51, 51));
        add_b1.setText("Add Items");
        add_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lb_product, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(tf_product, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(lb_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(add_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_qty)
                        .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_b1)))
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBackground(new java.awt.Color(255, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rice Variety", "Price", "Qty", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        print_b2.setBackground(new java.awt.Color(51, 102, 255));
        print_b2.setForeground(new java.awt.Color(255, 51, 51));
        print_b2.setSelected(true);
        print_b2.setText("Print");
        print_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_b2ActionPerformed(evt);
            }
        });

        exit_b3.setBackground(new java.awt.Color(51, 102, 255));
        exit_b3.setForeground(new java.awt.Color(255, 51, 51));
        exit_b3.setSelected(true);
        exit_b3.setText("Exit");
        exit_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_b3ActionPerformed(evt);
            }
        });

        jLabel3.setText("SubTotal");

        b2_delete.setBackground(new java.awt.Color(51, 102, 255));
        b2_delete.setForeground(new java.awt.Color(255, 51, 51));
        b2_delete.setText("Delete");
        b2_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2_deleteActionPerformed(evt);
            }
        });

        tf_mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mobilenoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(b2_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(exit_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lb_customername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(tf_customername, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(lb_mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(tf_mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(698, 698, 698)
                        .addComponent(print_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_customername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_customername)
                        .addComponent(lb_mobileno)
                        .addComponent(tf_mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        
    public void sales(){
        try {
            String subtotal=tf_subtotal.getText();
            int lastinsertedid=0;
            String url="jdbc:mysql://localhost:3306/friedriceshop";
            String uname="root";
            String password="xxxx";
            String query="INSERT into sales (subtotal)values(?)";
            conn=DriverManager.getConnection(url,uname,password);
            stmt1=conn.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            stmt1.setString(1,tf_subtotal.getText());
            stmt1.executeUpdate();
            ResultSet generatekey=stmt1.getGeneratedKeys();
            if(generatekey.next()){
            
                lastinsertedid=generatekey.getInt(1);
            
            }
           
            
            
            int rows= jTable1.getRowCount();
            String query1="INSERT into sales_product (sales_id,customer_Name,mobile_No,Rice_variety,price,Qty,Total) values(?,?,?,?,?,?,?)";
            stmt2=conn.prepareStatement(query1);
            String ricetype="";
            int price=0;
            int qty=0;
            int total=0;
            stmt2.setString(2,tf_customername.getText());
            stmt2.setString(3,tf_mobileno.getText());
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                ricetype=(String)jTable1.getValueAt(i,0);
                price=(int)jTable1.getValueAt(i,1);
                qty=(int)jTable1.getValueAt(i,2);
                total=(int)jTable1.getValueAt(i,3);
                stmt2.setInt(1, lastinsertedid);
                stmt2.setString(4,ricetype);
                stmt2.setInt(5,price);
                stmt2.setInt(6,qty);
                stmt2.setInt(7,total);
                stmt2.executeUpdate();
                
            }
            stmt2.addBatch();
           
           JOptionPane.showMessageDialog(this,"Sales Completed");
           HashMap a=new HashMap();
           a.put("invo", lastinsertedid);
            JasperDesign jdesign;
            try {
                jdesign = JRXmlLoader.load("file location of jrxml");
                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jprint;
                jprint = JasperFillManager.fillReport(jreport,a,conn);
                JasperViewer.viewReport(jprint);
                
            
            } 
            
            catch (JRException ex) {
                Logger.getLogger(BILLING.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            //JasperPrintManager.printReport(jprint,false);
        } catch (SQLException ex) {
            Logger.getLogger(BILLING.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    }
    private void exit_b3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       

    private void add_b1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
          int sum=0;
          if( tf_product.getSelectedIndex()== 0) {
              
                JOptionPane.showMessageDialog(this,"Select Product Name to Add","Error",JOptionPane.ERROR_MESSAGE);

          }
          else{
              if(tf_qty.getText().equals("")){
                  JOptionPane.showMessageDialog(this,"Add quantity level to add items","Error",JOptionPane.ERROR_MESSAGE);
              }
              else{
                   String rice;
                   rice = tf_product.getSelectedItem().toString();
                   int qty = Integer.parseInt(tf_qty.getText());
                   int price;
                   if(tf_product.getSelectedIndex()== 1){ 
                       price=20;
                   }
                   else if(tf_product.getSelectedIndex()== 2){
                       price=30;
                   }
                   else if(tf_product.getSelectedIndex()== 3){ 
                       price=200;
                   }
                   else if(tf_product.getSelectedIndex()== 4){ 
                       price=40;
                   }
                   else if(tf_product.getSelectedIndex()== 5){ 
                       price=100;
                   }
                   else if(tf_product.getSelectedIndex()== 6){ 
                       price=500;
                   }
                   else{
                       price=0;
                   }
              
              int total=price*qty;
              model= (DefaultTableModel)jTable1.getModel();
              model.addRow(new Object[]{rice,price,qty,total});
              }   
          }
          for(int i=0;i<jTable1.getRowCount();i++){
              sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
              
          }
          tf_subtotal.setText(Integer.toString(sum));
          tf_product.setSelectedIndex(0);
          tf_qty.setText("");
          
          
          
    }                                      
    
    private void tf_qtyKeyPressed(java.awt.event.KeyEvent evt) {                                  

    }                                 

    private void tf_qtyKeyReleased(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void tf_qtyKeyTyped(java.awt.event.KeyEvent evt) {                                

            char c=evt.getKeyChar();
            if(!Character.isDigit(c)){
                evt.consume();
        }// TODO add your handling code here:
    }                               

    private void print_b2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        sales();
        tf_customername.setText("");
        tf_mobileno.setText("");
        tf_product.setSelectedIndex(0);
        tf_qty.setText("");
        model.setRowCount(0);
        tf_subtotal.setText("");
        
    }                                        

    private void b2_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
         int sum=0;
        if(jTable1.getSelectedRow() != -1) {
               // remove selected row from the model
               model.removeRow(jTable1.getSelectedRow());
               for(int i=0;i<jTable1.getRowCount();i++){
              sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
              
          }
          tf_subtotal.setText(Integer.toString(sum));
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
            }

    }                                         

    private void tf_mobilenoActionPerformed(java.awt.event.ActionEvent evt) {                                            
         NumberFormat format = NumberFormat.getInstance();
         NumberFormatter formatter = new NumberFormatter(format);
         formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(10);
        formatter.setAllowsInvalid(false);
    // If you want the value to be committed on each keystroke instead of focus lost
       formatter.setCommitsOnValidEdit(true);
       JFormattedTextField field = new JFormattedTextField(formatter);

       JOptionPane.showMessageDialog(null, field);

    // getValue() always returns something valid
   // TODO add your handling code here:
    }                                           

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        int qty1=0;
        int total1=0;
        qty1 = Integer.parseInt(tf_qty.getText());
        model.setValueAt(qty1,jTable1.getSelectedRow(),2);
        int price=(int)jTable1.getValueAt(jTable1.getSelectedRow(),1);
        total1=price*qty1;
        model.setValueAt(total1,jTable1.getSelectedRow(),3);
        int sum=0;
        for(int i=0;i<jTable1.getRowCount();i++){
              sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
              
          }
         tf_subtotal.setText(Integer.toString(sum));
         tf_qty.setText("");
        JOptionPane.showMessageDialog(null, "Quantity is updated successfully");
        
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton add_b1;
    private javax.swing.JButton b2_delete;
    private javax.swing.JToggleButton exit_b3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_customername;
    private javax.swing.JLabel lb_mobileno;
    private java.awt.Label lb_product;
    private javax.swing.JLabel lb_qty;
    private javax.swing.JToggleButton print_b2;
    private javax.swing.JTextField tf_customername;
    private javax.swing.JFormattedTextField tf_mobileno;
    private javax.swing.JComboBox<String> tf_product;
    private javax.swing.JTextField tf_qty;
    private javax.swing.JTextField tf_subtotal;
    // End of variables declaration                   
}
